sudo: required
services:
  - docker

before_install:
  - docker build -t pahedu/docker-react -f Dockerfile.dev .

script:
  - docker run pahedu/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucker_name: "test"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
